### PR TITLE
Python3 support. Recent vim doesn't talk python2 anymore under ubuntu.

### PR DESCRIPTION
**Pull request by mimooh**
I managed to have bpy.autocomplete enabled in vim for testing via http://airplanes3d.net/pydev-000_e.xml solution. Well, I must say that's not really that useful, since after you typed bpy.<tab> you are still pretty much stuck with which option to choose next. The best place for that is just hovering stuff in blender GUI to get the hints for what's the name for this and that. Otherwise it is hard to figure out what bpy.pattern.you.are.really.looking.for.

### CODE REVIEW

**Comment by mipmip** [comment]
hmm. Now it breaks my vim,  :( I'm on OSX

```
Error detected while processing /Users/pim/.janus/vim-run-in-blender/ftplugin/python/vim_run_in_blender.vim:
line    4:
E319: Sorry, the command is not available in this version: python3 import sys
line    5:
E319: Sorry, the command is not available in this version: python3 import vim
line    6:
E319: Sorry, the command is not available in this version: python3 sys.path.append(vim.eval('expand("<sfile>:h")'))
```
Maybe you can try something with ```has('python') and has('python3')```?

**Comment by mimooh** [comment]
> hmm. Now it breaks my vim :(
> 
> ```
> Error detected while processing /Users/pim/.janus/vim-run-in-blender/ftplugin/python/vim_run_in_blender.vim:
> line    4:
> E319: Sorry, the command is not available in this version: python3 import sys
> line    5:
> E319: Sorry, the command is not available in this version: python3 import vim
> line    6:
> E319: Sorry, the command is not available in this version: python3 sys.path.append(vim.eval('expand("<sfile>:h")'))
> ```
> Maybe you can try something with ```has('python') and has('python3')```?

This is what I meant from the begining: there are two vims around. Mine is
+python3
-python

Yours is probably the other way around. One of the solutions is your
repo will be for python2 and mine for python3 for now. If you want to
provide both versions, then you must either provide two branches/folders
or have both blocks coded in you vimscript and served via if
python2/python3.


solidarny:~$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          

-- 
Karol Kreński
tel. 517-302-055

**Comment by mipmip** [comment]
Having 2 repo's of branches would be a little inefficient in my opinion. How about:

```vim
if has('python')
   python import ...
elseif if has('python3')
   python3 import ...
else
   finish
endif
```
Could you try this?

What is the other change you propose?
```
+    f = tempfile.NamedTemporaryFile(delete=False, mode='w')
      f.write(code+'\n')
      f.close()
  
 -    print f.name
 +    print (f.name)
```

**Comment by mipmip** [comment]
I thought I should ask: http://vi.stackexchange.com/questions/10913/elegant-way-to-support-both-python-and-python3-in-vim-plugin

**Comment by mipmip** [comment]
@mimooh did you see the proposal on http://vi.stackexchange.com/questions/10913/elegant-way-to-support-both-python-and-python3-in-vim-plugin ? Can you try to implement this in your pull request?

**Comment by mimooh** [comment]
> @mimooh did you see the proposal on http://vi.stackexchange.com/questions/10913/elegant-way-to-support-both-python-and-python3-in-vim-plugin ? Can you try to implement this in your pull request? 
Yes, seems reasonable.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
Let's try a different approach.

**Pull request closed without merging**
